config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  #get '/auth/:google_oauth2' => 'sessions#omniauth'
  
 

  
  
  resources :companies do
    collection do
      get 'search'
    end
  end
  resources :reviews
  resources :pizzas do
    
    resources :reviews, only: [:new, :index]
  end

  resources :users do
    resources :reviews, only:[:index]
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pizza.rb
class Pizza < ApplicationRecord
    belongs_to :company
    belongs_to :user 
    has_many :reviews
    has_many :users, through: :reviews #people who have reviewed it
    has_one_attached :image
  
    validates :name, presence: true
    validate :not_a_duplicate
  
    scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}
  
    def self.alpha
      order(:name)
    end
  
  
    def company_attributes=(attributes)
      self.company = Company.find_or_create_by(attributes) if !attributes['name'].empty?
      self.company
    end
  
    def thumbnail
      self.image.variant(resize: "100x100")
    end
  
    def not_a_duplicate
      pizza = Pizza.find_by(name: name)
      if !!pizza && pizza != self
        errors.add(:name, 'has already been added for that brand')
      end
    end
  
    def company_name
      company.try(:name)
    end
  
    def name_and_company
      "#{name} - #{company.try(:name)}"
    end
  
    #def self.search(search)
      #byebug
      #if search
        #pizza = Pizza.find_by(name: search)
        #if pizza
          #self.where(pizza_id: pizza)
      #else
        #self.all
      #end
    #end
    #end

  
  end

app/controllers/pizzas_controller.rb
# V - search form (on index view is fine) - look up difference between form for and form tag, and explain why form tag is an appropriate option
# M - class scope method to query the db on the pizza model
# C - index, or a new controller action of your creation
# route - either a new route, or instructions to go to an action that already exists(index)

class PizzasController < ApplicationController
    before_action :set_pizza, only:[:show, :edit, :update]
    before_action :redirect_if_not_logged_in
  
    def new
      @pizza = Pizza.new
      @pizza.build_company
    end
  
    def create
       @pizza = Pizza.new(pizza_params)
       @pizza.user_id = session[:user_id]
       
     
      if @pizza.save
        redirect_to pizza_path(@pizza)
      else
        render :new
      end
    end
  
    def index
      @pizza = Pizza.all
    end
  
    def show
     @user = User.find(session[:user_id])
     @pizza = Pizza.find_by_id(params[:id])
    
    end
  
    def edit
    end
  
    def update
      if @pizza.update(pizza_params)
        redirect_to pizza_path(@pizza)
      else
        render :edit
      end
    end

    def mypizzas
      @user = User.find(session[:user_id])
    end


    #def search  
      #if params[:search].blank?  
        #redirect_to(pizzas_path, error: "Empty field!") and return  
     # else  
        #@parameter = params[:search].downcase  
        #@pizza = Pizza.all.where("name LIKE :search", search: @parameter)
      #end  
    #end


  
    private
  
    def pizza_params
      params.require(:pizza).permit(:name, :description, :company_id, company_attributes: [:name])
    end
  
    def set_pizza
       @pizza = Pizza.find_by(params[:pizza_id])
       redirect_to pizzas_path if !@pizza
    end
  
  end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/pizzas/_form.html.erb
<% form_for(@pizza) do |f|%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <br>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <br>

  <p> Select a Company that already exists: </p>
  <div>
    <%= f.collection_select :company_id, Company.all, :id, :name, include_blank: 'Select One'%>

  </div>

  <p> Or create a new Company: </p>
  <div>
    <%=f.fields_for :company do |b| %>
      <%= b.label :name %>
      <%= b.text_field :name %>
    <% end %>
  </div>
  <br>
  <%= f.submit %>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Edit your Pizza</h1>


<%= form_for(@pizza) do |f| %>
 <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
 </div>
 <div>
  <%= f.label :description %>
  <%= f.text_field :description %>
 </div>

  <p>Select a Company that already exists:</p>
 <div>
    <%= f.collection_select :company_id, Company.all, :id, :name, include_blank: 'Select One'%>

 </div>


  <p>Or add a new Company:</p>
    <div>
        <%= f.fields_for :company do |p| %>
        <%= p.label :name %>
        <%= p.text_field :name %>

        <% end %>
    </div>

  <%= f.submit %>
<% end %>

app/views/pizzas/index.html.erb
<h1>PizzaMine Pizzas!</h1>

    <ol>
        <% @pizza.each do |p| %>
        
        <h2>Pizza Name:<%=  link_to "#{p.name}", pizza_path(p) %>  
        <%= link_to "Edit", edit_pizza_path(@pizza) if current_user == p.user %></h2>


        <h2>Company Name:<%= p.company.name %> </h2>

        <h3>Description: <%= p.description %></h3>

        <%= link_to "Review this Pizza!", new_pizza_review_path(p) %>
        <%= link_to "See All Reviews For this Pizza!", pizza_reviews_path(p) %>

    </ol>

<% end %>

app/views/pizzas/mypizzas.html.erb
<h1> testing out mypizza</h1>


<h1>Hello, <%= @user.username %>! Here are your Pizzas!</h1>

<% @user.each do |p| %>
    <%= p.name %>
    
<% end %>

app/views/pizzas/new.html.erb
<h1>Make A New Pizza!</h1>

<p><%= flash[:error] %></p>
<%= render partial: 'layouts/errors', locals: {object: @pizza}  %>

<%= form_for(@pizza) do |f| %>
 <div>
  <%= f.label :name %>
  <%= f.text_field :name %>
 </div>
 <div>
  <%= f.label :description %>
  <%= f.text_field :description %>
 </div>

  <p>Select a Company that already exists:</p>
 <div>
    <%= f.collection_select :company_id, Company.all, :id, :name, include_blank: 'Select Company'%>

 </div>


  <p>Or add a new Company:</p>
    <div>
        <%= f.fields_for :company do |p| %>
        <%= p.label :name %>
        <%= p.text_field :name %>

        <% end %>
    </div>

  <%= f.submit "Create" %>
<% end %>

app/views/pizzas/show.html.erb
<h1><%= @pizza.name %>  
<% if current_user == @pizza.user %>
<%= link_to "Edit", edit_pizza_path(@pizza) %></h1>
<% end %>
<h2> From: <%= @pizza.company.name %> </h2>
<div>
  <p><%= @pizza.description %></p>
</div>

<h3>Added by: <%= link_to "#{@pizza.user.username}", user_path(@user)%> </h3>

<br></br>
<%= link_to "Review this Pizza!", new_pizza_review_path(@pizza) %>
<p><%= link_to "See all Reviews", pizza_reviews_path(@pizza) %></p>