config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  #get '/auth/:google_oauth2' => 'sessions#omniauth'
  
 

  
  
  resources :companies do
    collection do
      get 'search'
    end
  end
  resources :reviews
  resources :pizzas do
    
    resources :reviews, only: [:new, :index]
  end

  resources :users do
    resources :reviews, only:[:index]
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :pizzas
    validates :name, presence: true, uniqueness: true
  
   
  
  end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

    def index
        @companies = Company.all
    end

    def search  
        if params[:search].blank?  
          redirect_to(companies_path, error: "Empty field!") and return  
        else  
          @parameter = params[:search].downcase
          @company = Company.find_by("name LIKE :search", search: @parameter)
          @pizza = Pizza.select{ |p| p[:company_id] == @company.id}
        
        end  
      end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/index.html.erb
<h1>Companies</h1>
<ol>
    <% @companies.each do |c| %>
    <li>
        <%= c.name %>    
        
        
    </li>
     <% end %>
</ol>
    

app/views/companies/search.html.erb
<h1>PizzaMine Pizzas!</h1>

    <ol>
        <% @pizza.each do |p| %>
        
        <h2>Pizza Name:<%=  link_to "#{p.name}", pizza_path(p) %>  
        


        <h2>Company Name:<%= p.company.name %> </h2>

        <h3>Description: <%= p.description %></h3>

        <%= link_to "Review this Pizza!", new_pizza_review_path(p) %>
        <%= link_to "See All Reviews For this Pizza!", pizza_reviews_path(p) %>

    </ol>

<% end %>