config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  #get '/auth/:google_oauth2' => 'sessions#omniauth'
  
 

  
  
  resources :companies do
    collection do
      get 'search'
    end
  end
  resources :reviews
  resources :pizzas do
    
    resources :reviews, only: [:new, :index]
  end

  resources :users do
    resources :reviews, only:[:index]
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :redirect_if_not_logged_in


  def new
    if @pizza = Pizza.find_by_id(params[:pizza_id])
      @review = @pizza.reviews.build
    else
      @review = Review.new
    end
  end

  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      redirect_to review_path(@review)
    else
      render :new
    end
  end
  
  def edit
    @review = Review.find_by_id(params[:id])
  end

  #def update
    #if @review.save
      #redirect_to review_path(@review)
    #else
      #render :new
    #end
  #end
  def update
    if @review.update(review_params)
      redirect_to review_path(@review)
    else
      render :edit
    end
  end

  def show
    @review = Review.find_by_id(params[:id])
  end

  def index
    
    if @pizza = Pizza.find_by_id(params[:pizza_id])
      #nested
      @reviews = @pizza.reviews
    else
    
      @reviews = Review.all
    end
  end

  private

  def review_params
      params.require(:review).permit(:pizza_id, :content, :stars, :title)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper

    def display_header(review)
      if params[:pizza_id]
          content_tag(:h1, "Add a Review for #{review.pizza.name} -  #{review.pizza.company.name}")
      else
        content_tag(:h1, "Create a review")
      end
    end
  end

app/views/reviews/edit.html.erb
<h1>Editting reviews</h1>

<p><%= flash[:error] %></p>

<%= form_for(@review) do |f|%>
  <% if params[:pizza_id] %>
    <%= f.hidden_field :pizza_id %>
  <% else %>
    <div>
      <%= f.label :pizza_id, "Select a Pizza" %>
      <%= f.collection_select :pizza_id, Pizza.alpha, :id, :name_and_company, include_blank: true %>
    </div>
  <% end %>
  <div>
    <%= f.label :stars %>
    <%= f.number_field :stars, min:0, max:5 %>
  </div>
  <br>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content, size: "25x10" %>
  </div>
  <br>



  <%= f.submit %>

<% end %>

app/views/reviews/index.html.erb
<% if @pizza %>
  <h1>Reviews for <%= @pizza.name%> - <%= @pizza.company_name%></h1>
<% else %>
  <h1>All the Reviews </h1>
<% end %>

<ul>
<% @reviews.each do |r| %>

  <li>
     <%= link_to r.title, review_path(r)%> - <%= r.stars%>
  </li> <br>

<% end %>
</ul>

app/views/reviews/new.html.erb
<%=  display_header(@review)%>

<%= render partial: 'layouts/errors', locals: {object: @review}  %>



<%= form_for(@review) do |f|%>
  <% if params[:pizza_id] %>
    <%= f.hidden_field :pizza_id %>
  <% else %>
    <div>
      <%= f.label :pizza_id, "Select a Pizza" %>
      <%= f.collection_select :pizza_id, Pizza.alpha, :id, :name_and_company, include_blank: true %>
    </div>
  <% end %>
  <div>
    <%= f.label :stars %>
    <%= f.number_field :stars, min:0, max:5 %>
  </div>
  <br>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content, size: "25x10" %>
  </div>
  <br>



  <%= f.submit %>

<% end %>

app/views/reviews/show.html.erb
<h1><%= "#{@review.title}" %></h1> 
<h2><%= @review.stars%> out of 5 Star Rating</h2>

<p><h2>Review:</h2> <%= @review.content%></p> 

<h3> Review made by: <%= "#{@review.user.username}" %>
<% if current_user == @review.user %>
<%= link_to "Edit", edit_review_path %>
    <% end %>