config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  #get '/auth/:google_oauth2' => 'sessions#omniauth'
  
 

  
  
  resources :companies do
    collection do
      get 'search'
    end
  end
  resources :reviews
  resources :pizzas do
    
    resources :reviews, only: [:new, :index]
  end

  resources :users do
    resources :reviews, only:[:index]
  end
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin_links.html.erb
<%= link_to "Log Out", logout_path, method: :delete %> |
<%= link_to "Add a Pizza", new_pizza_path %> |
<%= link_to "All Pizzas", pizzas_path %> |
<%= link_to "Add a Review", new_review_path %> |
<%= link_to "All Reviews", reviews_path %> |
<%= link_to "All Companies", companies_path %> |


<%= form_tag(search_companies_path, method: :get) do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search" %>
        </p>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<style>
  body{
    background-color: red
  }

</style>
  <head>
    <title>PizzaMine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

   <div><%= render_nav_bar %></div>

  <body>
    <%= yield %>
  </body>
</html>